// Copyright (C) 2022 George Cave.
//
// SPDX-License-Identifier: Apache-2.0

#ifndef FOE_GRAPHICS_RESOURCE_TYPE_DEFS_H
#define FOE_GRAPHICS_RESOURCE_TYPE_DEFS_H

#include <foe/type_defs.h>

#define FOE_GRAPHICS_RESOURCE_FUNCTIONALITY_ID FOE_PLUGIN_ID(1)

typedef enum foeGraphicsResourceStructureType {
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_IMAGE = 0,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_IMAGE_CREATE_INFO = 1,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_IMAGE_LOADER = 2,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_MATERIAL = 3,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_MATERIAL_CREATE_INFO = 4,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_MATERIAL_LOADER = 5,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_MESH = 6,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_MESH_FILE_CREATE_INFO = 7,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_MESH_CUBE_CREATE_INFO = 8,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_MESH_ICOSPHERE_CREATE_INFO = 9,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_MESH_LOADER = 10,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_SHADER = 11,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_SHADER_CREATE_INFO = 12,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_SHADER_LOADER = 13,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_VERTEX_DESCRIPTOR = 14,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_VERTEX_DESCRIPTOR_CREATE_INFO = 15,
    FOE_GRAPHICS_RESOURCE_STRUCTURE_TYPE_VERTEX_DESCRIPTOR_LOADER = 16,
} foeGraphicsResourceStructureType;

#endif // FOE_GRAPHICS_RESOURCE_TYPE_DEFS_H