// Copyright (C) 2022 George Cave.
//
// SPDX-License-Identifier: Apache-2.0

#ifndef FOE_PHYSICS_TYPE_DEFS_H
#define FOE_PHYSICS_TYPE_DEFS_H

#include <foe/simulation/type_defs.h>

#define FOE_PHYSICS_FUNCTIONALITY_ID FOE_SIMULATION_FUNCTIONALITY_ID(2)

typedef enum foePhysicsStructureType {
    // Resources
    FOE_PHYSICS_STRUCTURE_TYPE_COLLISION_SHAPE = FOE_PHYSICS_FUNCTIONALITY_ID,
    FOE_PHYSICS_STRUCTURE_TYPE_COLLISION_SHAPE_CREATE_INFO,
    FOE_PHYSICS_STRUCTURE_TYPE_COLLISION_SHAPE_LOADER,
    // Systems
    FOE_PHYSICS_STRUCTURE_TYPE_PHYSICS_SYSTEM,
    // Components
    FOE_PHYSICS_STRUCTURE_TYPE_RIGID_BODY_POOL,
} foePhysicsStructureType;

#endif // FOE_PHYSICS_TYPE_DEFS_H