/*
    Copyright (C) 2022 George Cave.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

// NOTE: This file was auto-generated by generate_vk_imgui_code.py

#ifndef FOE_GRAPHICS_VK_IMGUI_DISPLAY_VK_STRUCTS_HPP
#define FOE_GRAPHICS_VK_IMGUI_DISPLAY_VK_STRUCTS_HPP

#include <foe/graphics/vk/imgui/export.h>
#include <vulkan/vulkan.h>

#include <string>

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkDescriptorSetLayoutBinding(
    VkDescriptorSetLayoutBinding const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkDescriptorSetLayoutCreateInfo(
    VkDescriptorSetLayoutCreateInfo const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkVertexInputBindingDescription(
    VkVertexInputBindingDescription const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkVertexInputAttributeDescription(
    VkVertexInputAttributeDescription const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkPipelineVertexInputStateCreateInfo(
    VkPipelineVertexInputStateCreateInfo const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkPipelineInputAssemblyStateCreateInfo(
    VkPipelineInputAssemblyStateCreateInfo const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkPipelineTessellationStateCreateInfo(
    VkPipelineTessellationStateCreateInfo const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkPipelineRasterizationStateCreateInfo(
    VkPipelineRasterizationStateCreateInfo const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkPipelineColorBlendAttachmentState(
    VkPipelineColorBlendAttachmentState const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkPipelineColorBlendStateCreateInfo(
    VkPipelineColorBlendStateCreateInfo const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkStencilOpState(VkStencilOpState const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkPipelineDepthStencilStateCreateInfo(
    VkPipelineDepthStencilStateCreateInfo const &data);

FOE_GFX_VK_IMGUI_EXPORT void imgui_VkPushConstantRange(VkPushConstantRange const &data);

#endif // FOE_GRAPHICS_VK_IMGUI_DISPLAY_VK_STRUCTS_HPP